version: '1'

services:
  nginx-usersite:
    container_name: nginx-usersite
    image: nginx-usersite:0.0.1
    restart: always
    ports:
      - 80:9000
    depends_on:
      - usersite

  
  usersite:
    container_name: usersite
    image: usersite:0.0.1
    restart: always
    # user expose instead of ports to only allow
    # containers under docker compose access it instead of outside
    expose:
      - "8080"
    # ports:
    #   - 8080:9001